# インサートモードに入ったら読み込む {{{
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1
# }}}

# :Unite で読み込む {{{
[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = ['unite.vim']
# }}}

# tomlファイルだったら読み込む {{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
# }}}

# c/c++ファイルだったら読み込む {{{
[[plugins]]
repo =  'justmao945/vim-clang'
on_ft = 'c'

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = 'cpp'
# }}}
