set-option -g default-terminal screen-256color
set-option -g terminal-overrides 'xterm:colors=256'

set-option -g default-shell /usr/bin/fish

# ESCキーの効きを改善
set-option -s escape-time 0

# マウススクロールを許可
set-window-option -g mouse on

#ステータスラインを上に表示
set-option -g status-position top

#設定ファイルをリロードする
bind-key r source-file ~/.tmux.conf \; display "Reloaded!"

# peneの開始番号
set-option -g base-index 1

# ウィンドウ履歴の最大行数
set-option -g history-limit 10000

# コピーモードのキーバインドをvi風にする
set-window-option -g mode-keys vi
bind-key -t vi-copy v begin-selection

# ウィンドウのインデックスを1から始める
set-option -g base-index 1

# ペインの移動をvi風にする
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# ペインのリサイズをvi風にする
bind-key -r C-h resize-pane -L 5
bind-key -r C-l resize-pane -R 5
bind-key -r C-j resize-pane -D 5
bind-key -r C-k resize-pane -U 5

#
# キーバインド（コピーモード）
#
bind-key Space copy-mode
bind-key p paste-buffer

# vでマーク開始
bind-key -t vi-copy v begin-selection

# Vで行の先頭からマーク開始
bind-key -t vi-copy V select-line

# C-vで矩形選択の切り替え
bind-key -t vi-copy C-v rectangle-toggle

# yでヤンク
bind-key -t vi-copy y copy-selection

# Yで1行ヤンク
bind-key -t vi-copy Y copy-line


#
# 外観
#

# ステータスバーの色を設定する
set-option -g status-fg "colour255"
set-option -g status-bg "colour238"

# status-leftのフォーマットを指定する
set-option -g status-left '#[fg=colour255,bg=colour241] Session: #S #[default]'

# window-statusを中央揃えで配置する
set-option -g status-justify "centre"

set-window-option -g window-status-format " #I: #W "

# status-rightのフォーマットを指定する
set-option -g status-right '#[fg=colour255,bg=colour241] #h | %m/%d %H:%M '

# カレントウィンドウのwindow-statusのフォーマットを指定する
set-window-option -g window-status-current-format "#[fg=colour255,bg=colour4,bold] #I: #W #[default]"

# ペインボーダーの色を設定する
set-option -g pane-border-fg green
set-option -g pane-border-bg black
# アクティブなペインを目立たせる
set-option -g pane-active-border-fg white
set-option -g pane-active-border-bg yellow

# コマンドラインの色を設定する
set-option -g message-fg white
set-option -g message-bg black
set-option -g message-attr bright
