[tools]
bat = "latest"
node = "latest"
"npm:@google/gemini-cli" = "latest"
bottom = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
lazygit = "latest"
ripgrep = "latest"
starship = "latest"
yazi = "latest"
zoxide = "latest"
gh = "latest"
glow = "latest"
"aqua:b3nj5m1n/xdg-ninja" = "latest"
